### PR TITLE
Add support for factory resetting with USB disks

### PR DESCRIPTION
**Pull request by jovalle**

### CODE REVIEW

**Comment by jovalle** [comment]
@tolland, any objections?

**Comment by tolland** [comment]
Looks good. I've not had a chance to test it.

**Comment by jovalle** [comment]
Works spectacularly. 🙂 Merging.

**Comment by jovalle** [comment]
Seems I can't merge. Feel free to review when you have a moment. It works great. Using it in my homelab this past week.

**Pull request merged**
